---
title: "Corona Virus Report"
author:
- familyname: Vemagal
  othernames: Ankush
  address: Monash Universtidy
  email: 
  correspondingauthor: true
  qualifications:  XXX
- familyname: Kabu
  othernames: Ketan
  address: Monash University
  qualifications: XXX
- familyname: Lin
  othernames: Ruimin
  address: Monash University
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)

```



\section*{Country XX1 and YY1"}

\section*{Country XX2 and YY2}

\section3*{Country Japan and Singapore}

```{r read in data}
data <- read.csv("Data/worldwidecases.csv")
```

```{r data wrangling}

data1 <- data %>% 
  dplyr::filter(countriesAndTerritories %in% c("Japan", "Singapore"))

head(data1)
```

```{r table1}
table1 <- data1 %>% dplyr::select(cases) %>%
summary() %>%
kable(caption = "COVID19 case summary") %>%
kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r}
fig1 <- data1 %>% ggplot(aes(month, deaths)) + 
  geom_histogram(stat = "identity") + 
  facet_wrap(~ countriesAndTerritories, ncol = 1) +
  xlab("Month") + 
  ylab("Deaths")

fig1
```

